### PR TITLE
test: log.prefix should throw if changed

### LINKED ISSUE #15: Make log.prefix read-only
``` js
log = new Log('hoodie')
log.prefix // is 'hoodie'
log.prefix = 'foobar'
log.prefix // is still 'hoodie'
```

We use getters in other libraries already, like here in `hoodie-client`: https://github.com/hoodiehq/hoodie-client/blob/master/index.js#L16

---
- [x] claim this issue (@ianstalter123)
- [x] start a pull request (#22)
- [x] write tests
- [x] implement
- [x] update README
- [x] review & merge

Comment bellow, ping me in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/gr2m/) if you have any questions

### PR DESCRIPTION
**Pull request by ianstalter123**
pull request for hoodie client log added test to throw if prefix is changed

closes #15

### CODE REVIEW

**Comment by gr2m** [comment]
Can you mock Log.console as mentioned above? The rest is good to merge. I can also fix it if you are too busy?

**Comment by ianstalter123** [comment]
Yeah I will try to finish up by end of day,

Thanks

**Comment by ianstalter123** [comment]
@gr2m tried to fix it here but not sure if its perfect, you can fix if you are able to, thanks - -

**Comment by gr2m** [comment]
merged via 86e9502 :+1:

**Pull request closed without merging**
