### PR TITLE
test: log level will not set with invalid level

### PR DESCRIPTION
**Pull request by ianstalter123**
added a test to fail if the level changes when set to an invalid type

### CODE REVIEW

**Comment by gr2m** [comment]
This is great, thanks!

Could you throw an error instead of silently ignoring invalid values? Like

``` js
throw new Error('Invalid value for log.level: ' + newValue)
```

But we can also merge it in as is, and then make a follow up issue, as you prefer

**Comment by ianstalter123** [comment]
@gr2m  I could add that into an else statement as an additional commit but should I use fix: , format for the commit message to make it work with the versioning system

**Comment by gr2m** [comment]
I’d try to avoid else statements whenever possible, and use early `return`s or `throw`s instead, for better code readability. You could do this:

``` js
if (['debug', 'error', 'info', 'warn'].indexOf(newValue) === -1) {
  throw new Error('Invalid value for log.level: ' + newValue)
}

state.level = newValue
```

I would squash that change into the existing `fix: ...` commit. 

Does that all make sense? Let me know if you need help with anything :) Thanks a lot Ian

**Comment by ianstalter123** [comment]
@gr2m should be ok to merge

**Comment by gr2m** [comment]
merged via https://github.com/hoodiehq/hoodie-client-log/commit/1df2e63d8b42f1c6caf3333959ac092cd54bb46f :clap: 

I only changed the order of the two commits, so that we had a failing test first, and the fix second

**Pull request closed without merging**
