### PR TITLE
Update readme to improve "using in production"

### PR DESCRIPTION
**Pull request by elisechant**
Following this Issue: https://github.com/hoodiehq/hoodie-log/issues/40#issuecomment-368702007

In addition to this merged PR: https://github.com/hoodiehq/hoodie-log/pull/41

Includes information about how to access `process.env.NODE_ENV` in code.

### CODE REVIEW

**Comment by elisechant** [comment]
@gr2m I was wondering whether it would be better to include more info about NODE_ENV in the Readme. This is similar to what Redux Devtools Extension include - https://github.com/zalmoxisus/redux-devtools-extension#14-using-in-production Not sure how you guys at Hoodie feel about it.

**Comment by gr2m** [comment]
yeah I was wondering about it, I thought maybe instead of adding more information about that, we should avoid it in the first place.

Maybe just remove the if statement altogether and just leave 

```js
log.level = 'error';
```

Deciding whether an app is running in production or not is out of scope of hoodie.log

**Comment by elisechant** [comment]
@gr2m yeah I think that's sensible, let me fix.

**Comment by elisechant** [comment]
else we could use some pseduo code

```
if (isProduction) {
  log.level = 'error';
}
```

that way people won't accidentally disable for all environments

**Comment by gr2m** [comment]
sounds good, let’s do that

**Review by gr2m — APPROVED** [review]
sweet, cheers!

**Pull request merged**
